ERROR - 2021-12-10 21:39:49 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-12-10 21:39:49 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\pendataan\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\pendataan\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\pendataan\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\pendataan\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(241): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptForgot()
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-12-10 21:39:49 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
