ERROR - 2021-12-02 01:58:38 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-12-02 01:58:38 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\pendataan\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\pendataan\system\Database\BaseBuilder.php(1527): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\xampp\htdocs\pendataan\system\Model.php(509): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#3 C:\xampp\htdocs\pendataan\system\BaseModel.php(1084): CodeIgniter\Model->countAllResults(false)
#4 C:\xampp\htdocs\pendataan\app\Controllers\Dashboard.php(27): CodeIgniter\BaseModel->paginate(5, 'penduduk')
#5 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): App\Controllers\Dashboard->datapenduduk()
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-12-02 01:58:38 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Dashboard), true)
#2 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-02 04:52:00 --> Class 'Codeigniter\Validation\Rules' not found
#0 C:\xampp\htdocs\pendataan\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xampp\htdocs\pendataan\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(161): CodeIgniter\Controller->validate(Array)
#3 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#4 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2021-12-02 04:55:54 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-12-02 04:55:54 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\pendataan\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\pendataan\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\pendataan\system\Validation\Rules.php(161): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\pendataan\system\Validation\Validation.php(277): CodeIgniter\Validation\Rules->is_unique('hamzahrisvi27', 'username', Array, NULL)
#4 C:\xampp\htdocs\pendataan\system\Validation\Validation.php(151): CodeIgniter\Validation\Validation->processRules('username', 'username', 'hamzahrisvi27', Array, Array)
#5 C:\xampp\htdocs\pendataan\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(161): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2021-12-02 04:55:54 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\pendataan\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\pendataan\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-12-02 04:57:02 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-12-02 05:03:15 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\pendataan\system\Common.php(937): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-12-02 05:17:16 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\pendataan\system\Common.php(937): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-12-02 05:27:50 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\pendataan\system\Common.php(937): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-12-02 20:26:03 --> Class name must be a valid object or a string
#0 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\pendataan\system\Common.php(937): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-12-02 20:48:33 --> Class '' not found
#0 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator(Object(Myth\Auth\Config\Auth), false)
#1 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#2 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Config\Services.php(86): CodeIgniter\Config\BaseService::getSharedInstance('activator', NULL)
#3 C:\xampp\htdocs\pendataan\system\Config\BaseService.php(248): Myth\Auth\Config\Services::activator()
#4 C:\xampp\htdocs\pendataan\system\Common.php(937): CodeIgniter\Config\BaseService::__callStatic('activator', Array)
#5 C:\xampp\htdocs\pendataan\vendor\myth\auth\src\Controllers\AuthController.php(195): service('activator')
#6 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\pendataan\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pendataan\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pendataan\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
